language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
  -  rust: nightly
addons:
    apt:
        packages:
            - libssl-dev
sudo: true
install:
  - sudo apt-get install -y libdbus-1-dev openssl
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    fi
  - rustc -V
script:
  - cargo build
  - RUST_TEST_THREADS=1 cargo test -- --nocapture
  - |
    # tarpaulin deps
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
    fi
